### ISSUE TITLE
Content difficult to read in dark mode

### ISSUE THREAD

**Issue by mike-healy** [iconara/athena-guide-content#15]
Thanks for your article about `MAX_BY`, very useful!

The theme does not seem to work well if the user has system dark mode enabled.

![Screenshot 2024-12-12 at 10 58 02 AM](https://github.com/user-attachments/assets/b7770aae-2f7c-4232-aed9-e14c49625ff0)

**Comment by iconara** [comment]
Thank you for reporting this. It should be fixed now. I hadn't properly disabled automatic dark mode in Vitepress.

**Comment by mike-healy** [comment]
Awesome, thank you
